[build]
  command = "npm run build"
  publish = "web"

[build.environment]
    NODE_ENV = 'development'
    NODE_VERSION = '18.17.1'
    NPM_VERSION = '10.0.0'

[[redirects]]
from = "https://dontpanicipsum.herebedragons.world/*"
to = "https://dontpanicipsum.moritzlost.de/:splat"
status = 301
force = true
